# Generated by Django 5.2.7 on 2025-11-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_sms_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
