# Generated by Django 5.2.7 on 2025-12-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_wallet_balance_delete_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_avatar_url',
            field=models.URLField(blank=True, help_text='Avatar URL from Google/Social', max_length=500, null=True),
        ),
    ]
