# Generated by Django 5.2.7 on 2025-12-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_social_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcome_status',
            field=models.BooleanField(default=True, help_text='True if new user needs welcome modal'),
        ),
    ]
