# Generated by Django 5.2.7 on 2025-12-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmotp_email', models.EmailField(max_length=255)),
                ('farmotp_value', models.CharField(max_length=10)),
                ('farmotp_type', models.CharField(max_length=50)),
                ('farmotp_create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Farm OTP',
                'verbose_name_plural': 'Farm OTPs',
            },
        ),
    ]
