# Generated by Django 5.2.7 on 2025-12-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmotp',
            name='farmotp_usage',
            field=models.BooleanField(default=False),
        ),
    ]
